give  Mon  5 Apr 02:57:09 AEST 2021: Fixed up a whole heap of error checking stuff with most of my scripts

diff --git a/girt-add~ b/girt-add~
--- a/girt-add~
+++ b/girt-add~
@@ -6,13 +6,27 @@ if [ ! -d .girt ]; then
     exit 1
 fi
 
-# Make sure that girt-add is given at least 1 command line argument
+# Make sure that girt-add is given at least 1 command line argument and that no 
+# command line argument starts with -[a-zA-Z._] or --.
 if [ "$#" -eq 0 ]; then
     echo "usage: "$0" <filenames>"
+    exit 1
 fi
+for arg in "$@"; do
+    if echo "$arg" | grep -E -q '^-[a-zA-Z._]' || echo "$arg" | grep -E -q '^--.'; then
+        echo "usage: "$0" <filenames>"
+        exit 1
+    fi
+done
 
 
 for filename in $@; do
+    # Test that filename is valid
+    if echo "$filename" | grep -E -q '^[._-]'; then
+        echo ""$0": error: invalid filename '"$filename"'"
+        exit 1
+    fi
+    
     # Test that filename refers to a file that exists
     if [ ! -e "$filename" ]; then
         echo ""$0": error: can not open '"$filename"'"
@@ -27,5 +41,3 @@ for filename in $@; do
     
     cp "$filename" .girt/index
 done
-
-echo "testinggggggggggggg"
diff --git a/girt-show~ b/girt-show~
--- a/girt-show~
+++ b/girt-show~
@@ -27,8 +27,14 @@ if [ "$commit_number" != "" -a ! -d .girt/commits/"commit "$commit_number"" ]; t
     exit 1
 fi
 
-# Make sure that the filename specified exists in the commit or index
+# Test that the file name provided is valid
 filename="$(echo "$1" | cut -d: -f2)"
+if echo "$filename" | grep -E -q '^[._-]'; then
+    echo ""$0": error: invalid filename '"$filename"'"
+    exit 1
+fi
+
+# Make sure that the filename specified exists in the commit or index
 if [ "$commit_number" = "" -a ! -f ".girt/index/"$filename"" ]; then
     echo ""$0": error: '"$filename"' not found in index"
     exit 1
