give  Tue  6 Apr 03:35:56 AEST 2021: Worked on more test scripts and fixed up a couple of minor bugs

diff --git a/girt-commit~ b/girt-commit~
--- a/girt-commit~
+++ b/girt-commit~
@@ -2,13 +2,13 @@
 
 # Make sure there has been a previous init
 if [ ! -d .girt ]; then
-    echo ""$0": error: girt repository directory .girt not found"
+    echo ""$0": error: girt repository directory .girt not found" 1>&2
     exit 1
 fi
 
 # Make sure that the syntax for the inputted command line arguments is correct
 if [ "$#" -ne 2 -a "$#" -ne 3 ]; then
-    echo "usage: "$0" [-a] -m commit-message"
+    echo "usage: "$0" [-a] -m commit-message" 1>&2
     exit 1
 else
     if [ "$#" -eq 2 ] && [ "$1" = "-m" ] &&  \
@@ -18,7 +18,7 @@ else
     ! ( echo "$3" | grep -E -q '^-[a-zA-Z._]' || echo "$3" | grep -E -q '^--.' ); then
         :
     else   
-        echo "usage: "$0" [-a] -m commit-message"
+        echo "usage: "$0" [-a] -m commit-message" 1>&2
         exit 1
     fi
 fi
@@ -51,12 +51,12 @@ fi
 # Check that there have been changes in the index since the most recent commit
 if [ "$new_commit_name" = "commit 0" ]; then
     if [ -z "$(ls .girt/index)" ]; then
-        echo "nothing to commit"
+        echo "nothing to commit" 1>&2
         exit 1
     fi
 else
     if diff -r .girt/index .girt/commits/"$prev_commit_name" > /dev/null; then
-        echo "nothing to commit"
+        echo "nothing to commit" 1>&2
         exit 1
     fi
 fi
diff --git a/girt-show~ b/girt-show~
--- a/girt-show~
+++ b/girt-show~
@@ -2,13 +2,13 @@
 
 # Make sure there has been a previous init
 if [ ! -d .girt ]; then
-    echo ""$0": error: girt repository directory .girt not found"
+    echo ""$0": error: girt repository directory .girt not found" 1>&2
     exit 1
 fi
 
 # Make sure that there is only 1 command line argument given
 if [ "$#" -ne 1 ]; then
-    echo "usage: "$0" <commit>:<filename>"
+    echo "usage: "$0" <commit>:<filename>" 1>&2
     exit 1
 fi
 
@@ -16,36 +16,40 @@ fi
 if echo "$1" | grep -E -q '[^:]*:[^:]*'; then
     :
 else
-    echo ""$0": error: invalid object "$1""
+    echo ""$0": error: invalid object "$1"" 1>&2
     exit 1
 fi
 
 # Make sure that if there is an integer provided, it is the number of an existing commit
 commit_number="$(echo "$1" | cut -d: -f1)"
 if [ "$commit_number" != "" -a ! -d .girt/commits/"commit "$commit_number"" ]; then
-    echo ""$0": error: unknown commit '"$commit_number"'"
+    echo ""$0": error: unknown commit '"$commit_number"'" 1>&2
     exit 1
 fi
 
 # Test that the file name provided is valid
 filename="$(echo "$1" | cut -d: -f2)"
 if echo "$filename" | grep -E -q '^[._-]'; then
-    echo ""$0": error: invalid filename '"$filename"'"
+    echo ""$0": error: invalid filename '"$filename"'" 1>&2
     exit 1
 fi
 
 # Make sure that the filename specified exists in the commit or index
 if [ "$commit_number" = "" -a ! -f ".girt/index/"$filename"" ]; then
-    echo ""$0": error: '"$filename"' not found in index"
+    echo ""$0": error: '"$filename"' not found in index" 1>&2
     exit 1
 elif [ "$commit_number" != "" -a ! -f ".girt/commits/commit "$commit_number"/"$filename"" ]; then
-    echo ""$0": error: '"$filename"' not found in commit "$commit_number""
+    echo ""$0": error: '"$filename"' not found in commit "$commit_number"" 1>&2
     exit 1
 fi
 
-# Print the contents of filename as of the specified commit
+# Print the contents of filename as of the specified commit, as long as the file is not empty
 if [ "$commit_number" = "" ]; then
-    echo "$(cat .girt/index/"$filename")"
+    if [ ! -z "$(echo "$(cat .girt/index/"$filename")")" ]; then
+        echo "$(cat .girt/index/"$filename")"
+    fi
 else
-    echo "$(cat .girt/commits/"commit "$commit_number""/"$filename")"
+    if [ ! -z "$(echo "$(cat .girt/commits/"commit "$commit_number""/"$filename")")" ]; then
+        echo "$(cat .girt/commits/"commit "$commit_number""/"$filename")"
+    fi
 fi
