give  Tue  6 Apr 01:16:11 AEST 2021: Started working on test scripts and fixed up some errors that this showed me

diff --git a/girt-add~ b/girt-add~
--- a/girt-add~
+++ b/girt-add~
@@ -2,19 +2,19 @@
 
 # Make sure there has been a previous init
 if [ ! -d .girt ]; then
-    echo ""$0": error: girt repository directory .girt not found"
+    echo ""$0": error: girt repository directory .girt not found" 1>&2
     exit 1
 fi
 
 # Make sure that girt-add is given at least 1 command line argument and that no 
 # command line argument starts with -[a-zA-Z._] or --.
 if [ "$#" -eq 0 ]; then
-    echo "usage: "$0" <filenames>"
+    echo "usage: "$0" <filenames>" 1>&2
     exit 1
 fi
 for arg in "$@"; do
     if echo "$arg" | grep -E -q '^-[a-zA-Z._]' || echo "$arg" | grep -E -q '^--.'; then
-        echo "usage: "$0" <filenames>"
+        echo "usage: "$0" <filenames>" 1>&2
         exit 1
     fi
 done
@@ -23,7 +23,7 @@ done
 for filename in $@; do
     # Test that filename is valid
     if echo "$filename" | grep -E -q '^[._-]'; then
-        echo ""$0": error: invalid filename '"$filename"'"
+        echo ""$0": error: invalid filename '"$filename"'" 1>&2
         exit 1
     fi
     
@@ -33,7 +33,7 @@ for filename in $@; do
     # If it is in the current directory then test that it is an ordinary file
     if [ -e "$filename" ]; then
         if [ ! -f "$filename" ]; then
-            echo ""$0": error: invalid filename '"$filename"'"
+            echo ""$0": error: '"$filename"' is not a regular file" 1>&2
             exit 1
         else
             cp "$filename" .girt/index
@@ -41,7 +41,7 @@ for filename in $@; do
     elif [ -e .girt/index/"$filename" ]; then
         rm .girt/index/"$filename"
     else
-        echo ""$0": error: can not open '"$filename"'"
+        echo ""$0": error: can not open '"$filename"'" 1>&2
         exit 1
     fi
 done
diff --git a/girt-init~ b/girt-init~
--- a/girt-init~
+++ b/girt-init~
@@ -2,12 +2,13 @@
 
 # Check that there are no command line arguments given
 if [ "$#" -gt 0 ]; then
-    echo "usage: "$0""
+    echo "usage: "$0"" 1>&2
     exit 1
 fi
 
+
 if [ -d .girt ]; then
-    echo ""$0": error: .girt already exists"
+    echo ""$0": error: .girt already exists" 1>&2
     exit 1
 fi
 
diff --git a/girt-rm b/girt-rm
--- a/girt-rm
+++ b/girt-rm
@@ -2,21 +2,21 @@
 
 # Make sure there has been a previous init
 if [ ! -d .girt ]; then
-    echo ""$0": error: girt repository directory .girt not found"
+    echo ""$0": error: girt repository directory .girt not found" 1>&2
     exit 1
 fi
 
 # Check that after any --force or --cached options there is at least one file given to remove from index
 if [ "$#" -eq 0 ]; then
-    echo "usage: "$0" [--force] [--cached] <filenames>"
+    echo "usage: "$0" [--force] [--cached] <filenames>" 1>&2
     exit 1
 elif [ "$1" = "--force" ]; then
     if [ "$#" -eq 1 ]; then
-        echo "usage: "$0" [--force] [--cached] <filenames>"
+        echo "usage: "$0" [--force] [--cached] <filenames>" 1>&2
         exit 1
     elif [ "$2" = "--cached" ]; then
         if [ "$#" -eq 2 ]; then
-            echo "usage: "$0" [--force] [--cached] <filenames>"
+            echo "usage: "$0" [--force] [--cached] <filenames>" 1>&2
             exit 1
         else
             filename_arg_start_no=3
@@ -26,7 +26,7 @@ elif [ "$1" = "--force" ]; then
     fi
 elif [ "$1" = "--cached" ]; then
     if [ "$#" -eq 1 ]; then
-        echo "usage: "$0" [--force] [--cached] <filenames>"
+        echo "usage: "$0" [--force] [--cached] <filenames>" 1>&2
         exit 1  
     else
         filename_arg_start_no=2
@@ -40,7 +40,7 @@ arg_no=1 # Since shell command line arguments start with $1
 for arg in "$@"; do
     if ( echo "$arg" | grep -E -q '^-[a-zA-Z._]' || echo "$arg" | grep -E -q '^--.' ) && \
     [ "$arg_no" -ge "$filename_arg_start_no" ]; then
-        echo "usage: "$0" [--force] [--cached] <filenames>"
+        echo "usage: "$0" [--force] [--cached] <filenames>" 1>&2
         exit 1
     fi
     arg_no="$((arg_no + 1))"
@@ -56,13 +56,13 @@ for filename in "$@"; do
 
     # Test that filename is valid
     if echo "$filename" | grep -E -q '^[._-]'; then
-        echo ""$0": error: invalid filename '"$filename"'"
+        echo ""$0": error: invalid filename '"$filename"'" 1>&2
         exit 1
     fi
     
     # Test that filename refers to a file which exists within the index
     if [ ! -e .girt/index/"$filename" ]; then
-        echo ""$0": error: '"$filename"' is not in the girt repository"
+        echo ""$0": error: '"$filename"' is not in the girt repository" 1>&2
         exit 1
     fi
     
@@ -103,18 +103,18 @@ for filename in "$@"; do
     if [ "$1" != "--force" ]; then
         if [ "$1" = "--cached" ]; then
             if [ "$matches_curr_dir" = "false" -a "$matches_most_recent" = "false" ]; then
-                echo ""$0": error: '"$filename"' in index is different to both to the working file and the repository"
+                echo ""$0": error: '"$filename"' in index is different to both to the working file and the repository" 1>&2
                 exit 1
             fi
         else # No options were given
             if [ "$matches_curr_dir" = "false" -a "$matches_most_recent" = "false" ]; then
-                echo ""$0": error: '"$filename"' in index is different to both to the working file and the repository"
+                echo ""$0": error: '"$filename"' in index is different to both to the working file and the repository" 1>&2
                 exit 1
             elif [ "$matches_curr_dir" = "true" -a "$matches_most_recent" = "false" ]; then
-                echo ""$0": error: '"$filename"' has staged changes in the index"
+                echo ""$0": error: '"$filename"' has staged changes in the index" 1>&2
                 exit 1
             elif [ "$matches_curr_dir" = "false" -a "$matches_most_recent" = "true" ]; then
-                echo ""$0": error: '"$filename"' in the repository is different to the working file"
+                echo ""$0": error: '"$filename"' in the repository is different to the working file" 1>&2
                 exit 1
             fi
         fi
