give  Sat  3 Apr 13:11:43 AEDT 2021: Finished girt-commit and girt-log from subset 0

diff --git a/girt-init~ b/girt-init~
--- a/girt-init~
+++ b/girt-init~
@@ -1,12 +1,19 @@
 #!/bin/dash
 
+# Check that there are no command line arguments given
+if [ "$#" -gt 0 ]; then
+    echo "usage: "$0""
+    exit 1
+fi
+
 if [ -d .girt ]; then
-    echo "girt-init: error: .girt already exists"
+    echo ""$0": error: .girt already exists"
     exit 1
 fi
 
 mkdir .girt
 mkdir .girt/index
 mkdir .girt/commits
+echo "" > .girt/commit_messages.txt
 
 echo "Initialized empty girt repository in .girt"
